"""Add admin role

Revision ID: 935d31c238b2
Revises: 1ac39112255d
Create Date: 2026-05-02 09:15:39.926923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '935d31c238b2'
down_revision: Union[str, Sequence[str], None] = '1ac39112255d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'admin';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
